name: Create Release

on:
  # push:
  #   tags:
  #     - 'v*'
      
  workflow_dispatch:
    inputs:
      tag:
        description: 'Target Tag for Release'
        type: string
        required: true
      force:
        description: 'Force Release?'
        type: boolean
        required: false
        default: false

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}
      - name: Create Release with Changelog
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          name: Release ${{ github.event.inputs.tag || github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
